import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const DEFAULT_SETTINGS = { local_enabled:true, drive_enabled:false, interval_hours:24, last_run_at:null, last_success_at:null, last_status:'never', last_message:'Nie wykonano jeszcze automatycznej kopii.' };
const ALLOWED_INTERVALS = new Set([0,1,6,12,24,72,168]);

function writePrivateJson(file,value){fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,JSON.stringify(value,null,2),{encoding:'utf8',mode:0o600});try{fs.chmodSync(file,0o600);}catch{/* Windows nie obsługuje bitów POSIX. */}}
async function responseJson(response,label){const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error_description||data.error?.message||`${label}: HTTP ${response.status}`);return data;}
function friendlyFilename(date,trigger){const pad=(value,size=2)=>String(value).padStart(size,'0'),labels={manual:'ręczna',schedule:'automatyczna',before_restore:'przed przywróceniem'},label=labels[trigger]||'ręczna';return `CRESCI - ${label} - ${pad(date.getDate())}-${pad(date.getMonth()+1)}-${date.getFullYear()}, ${pad(date.getHours())}.${pad(date.getMinutes())}.${pad(date.getSeconds())}.${pad(date.getMilliseconds(),3)}.json`;}
function friendlyLegacyName(name){const match=name.match(/^cresci-backup-(\d{4})-(\d{2})-(\d{2})T(\d{2})-(\d{2})-(\d{2})-(\d{3})Z\.json$/i);if(!match)return null;const[,year,month,day,hour,minute,second,millisecond]=match,date=new Date(`${year}-${month}-${day}T${hour}:${minute}:${second}.${millisecond}Z`);return Number.isNaN(date.getTime())?null:friendlyFilename(date,'manual');}
function validateBackup(payload){if(payload?.format!=='gym-progress-backup'||!Array.isArray(payload.profiles)||!Array.isArray(payload.exercises)||!Array.isArray(payload.progress_entries))throw new Error('Wybrany plik nie jest prawidłową kopią CRESCI.');return payload;}

export class LocalFileProvider{
  constructor(directory){this.directory=directory;}
  async save(payload,filename){fs.mkdirSync(this.directory,{recursive:true});const target=path.join(this.directory,filename);fs.writeFileSync(target,JSON.stringify(payload,null,2),'utf8');return{provider:'local',filename,path:target};}
  safePath(filename){if(!filename||path.basename(filename)!==filename)throw new Error('Nieprawidłowa nazwa kopii.');const target=path.resolve(this.directory,filename),root=path.resolve(this.directory)+path.sep;if(!target.startsWith(root))throw new Error('Nieprawidłowa nazwa kopii.');return target;}
  async list(){if(!fs.existsSync(this.directory))return[];return fs.readdirSync(this.directory,{withFileTypes:true}).filter(entry=>entry.isFile()&&entry.name.toLowerCase().endsWith('.json')).map(entry=>{const stat=fs.statSync(this.safePath(entry.name));return{provider:'local',name:entry.name,created_at:stat.mtime.toISOString(),size:stat.size};}).sort((a,b)=>b.created_at.localeCompare(a.created_at));}
  async load(filename){return validateBackup(JSON.parse(fs.readFileSync(this.safePath(filename),'utf8')));}
  async rename(filename,newName){const source=this.safePath(filename),target=this.safePath(newName);if(source!==target)fs.renameSync(source,target);return newName;}
  async prune(keep=3){const files=await this.list(),removed=[];for(const file of files.slice(keep)){fs.unlinkSync(this.safePath(file.name));removed.push(file.name);}return removed;}
}

export class GoogleDriveProvider{
  constructor({tokenPath,clientId,clientSecret,fetchImpl=fetch}){this.tokenPath=tokenPath;this.clientId=clientId;this.clientSecret=clientSecret;this.fetchImpl=fetchImpl;this.states=new Map();}
  get configured(){return Boolean(this.clientId&&this.clientSecret);}
  configure({clientId,clientSecret}){if(clientId)this.clientId=clientId;if(clientSecret)this.clientSecret=clientSecret;}
  async googleFetch(url,options,label){try{return await this.fetchImpl(url,options);}catch(error){const detail=error.cause?.code||error.cause?.message||error.message;throw new Error(`${label}: nie udało się połączyć z Google (${detail}).`);}}
  readToken(){try{return JSON.parse(fs.readFileSync(this.tokenPath,'utf8'));}catch{return null;}}
  writeToken(token){writePrivateJson(this.tokenPath,token);}
  status(){return{configured:this.configured,connected:Boolean(this.readToken()?.refresh_token),client_id:this.clientId||''};}
  authorizationUrl(redirectUri){if(!this.configured)throw new Error('Najpierw skonfiguruj GOOGLE_CLIENT_ID i GOOGLE_CLIENT_SECRET.');const state=crypto.randomBytes(24).toString('hex');this.states.set(state,{redirectUri,expires:Date.now()+10*60*1000});const query=new URLSearchParams({client_id:this.clientId,redirect_uri:redirectUri,response_type:'code',scope:'https://www.googleapis.com/auth/drive.file',access_type:'offline',prompt:'consent',include_granted_scopes:'true',state});return`https://accounts.google.com/o/oauth2/v2/auth?${query}`;}
  async finishAuthorization({code,state}){const pending=this.states.get(state);this.states.delete(state);if(!pending||pending.expires<Date.now())throw new Error('Sesja łączenia z Google wygasła. Spróbuj ponownie.');const response=await this.googleFetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:this.clientId,client_secret:this.clientSecret,redirect_uri:pending.redirectUri,grant_type:'authorization_code'}),signal:AbortSignal.timeout(15_000)},'Autoryzacja Google');const token=await responseJson(response,'Autoryzacja Google');if(!token.refresh_token)throw new Error('Google nie zwróciło tokenu offline. Odłącz aplikację w ustawieniach konta Google i połącz ponownie.');this.writeToken({refresh_token:token.refresh_token,access_token:token.access_token,expires_at:Date.now()+token.expires_in*1000,folder_id:null});}
  disconnect(){if(fs.existsSync(this.tokenPath))fs.unlinkSync(this.tokenPath);}
  async accessToken(){const stored=this.readToken();if(!stored?.refresh_token)throw new Error('Google Drive nie jest połączony.');if(stored.access_token&&stored.expires_at>Date.now()+60_000)return stored.access_token;const response=await this.googleFetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:this.clientId,client_secret:this.clientSecret,refresh_token:stored.refresh_token,grant_type:'refresh_token'}),signal:AbortSignal.timeout(15_000)},'Odświeżenie połączenia Google');const token=await responseJson(response,'Odświeżenie połączenia Google');this.writeToken({...stored,access_token:token.access_token,expires_at:Date.now()+token.expires_in*1000});return token.access_token;}
  async ensureFolder(accessToken){const stored=this.readToken();if(stored?.folder_id){const check=await this.googleFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(stored.folder_id)}?fields=id,name,trashed`,{headers:{Authorization:`Bearer ${accessToken}`},signal:AbortSignal.timeout(15_000)},'Sprawdzanie folderu Google Drive');if(check.ok){const folder=await responseJson(check,'Sprawdzanie folderu Google Drive');if(!folder.trashed)return folder.id;}else if(check.status!==404)await responseJson(check,'Sprawdzanie folderu Google Drive');this.writeToken({...stored,folder_id:null});}const response=await this.googleFetch('https://www.googleapis.com/drive/v3/files?fields=id,name',{method:'POST',headers:{Authorization:`Bearer ${accessToken}`,'Content-Type':'application/json'},body:JSON.stringify({name:'CRESCI Backups',mimeType:'application/vnd.google-apps.folder'}),signal:AbortSignal.timeout(15_000)},'Tworzenie folderu Google Drive');const folder=await responseJson(response,'Tworzenie folderu Google Drive');this.writeToken({...this.readToken(),folder_id:folder.id});return folder.id;}
  async save(payload,filename){const accessToken=await this.accessToken(),folderId=await this.ensureFolder(accessToken),boundary=`cresci_${crypto.randomBytes(12).toString('hex')}`;const metadata=JSON.stringify({name:filename,parents:[folderId],mimeType:'application/json'}),data=JSON.stringify(payload,null,2);const body=Buffer.from(`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${metadata}\r\n--${boundary}\r\nContent-Type: application/json\r\n\r\n${data}\r\n--${boundary}--`);const response=await this.googleFetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink',{method:'POST',headers:{Authorization:`Bearer ${accessToken}`,'Content-Type':`multipart/related; boundary=${boundary}`},body,signal:AbortSignal.timeout(30_000)},'Wysyłanie kopii do Google Drive');const file=await responseJson(response,'Wysyłanie kopii do Google Drive');return{provider:'drive',filename,id:file.id,webViewLink:file.webViewLink||null};}
  async list(){const accessToken=await this.accessToken(),folderId=await this.ensureFolder(accessToken),query=new URLSearchParams({q:`'${folderId}' in parents and trashed = false`,orderBy:'createdTime desc',pageSize:'100',fields:'files(id,name,createdTime,size)'}),response=await this.googleFetch(`https://www.googleapis.com/drive/v3/files?${query}`,{headers:{Authorization:`Bearer ${accessToken}`},signal:AbortSignal.timeout(15_000)},'Pobieranie listy kopii z Google Drive'),data=await responseJson(response,'Pobieranie listy kopii z Google Drive');return(data.files||[]).filter(file=>file.name?.toLowerCase().endsWith('.json')).map(file=>({provider:'drive',id:file.id,name:file.name,created_at:file.createdTime,size:Number(file.size)||null}));}
  async load(id){const files=await this.list(),file=files.find(item=>item.id===id);if(!file)throw new Error('Nie znaleziono wybranej kopii na Google Drive.');const accessToken=await this.accessToken(),response=await this.googleFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?alt=media`,{headers:{Authorization:`Bearer ${accessToken}`},signal:AbortSignal.timeout(30_000)},'Pobieranie kopii z Google Drive');return validateBackup(await responseJson(response,'Pobieranie kopii z Google Drive'));}
  async rename(id,newName){const accessToken=await this.accessToken(),response=await this.googleFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(id)}?fields=id,name`,{method:'PATCH',headers:{Authorization:`Bearer ${accessToken}`,'Content-Type':'application/json'},body:JSON.stringify({name:newName}),signal:AbortSignal.timeout(15_000)},'Zmiana nazwy kopii na Google Drive');return responseJson(response,'Zmiana nazwy kopii na Google Drive');}
  async prune(keep=3){const accessToken=await this.accessToken(),files=await this.list(),removed=[];for(const file of files.slice(keep)){const response=await this.googleFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(file.id)}`,{method:'DELETE',headers:{Authorization:`Bearer ${accessToken}`},signal:AbortSignal.timeout(15_000)},'Usuwanie starej kopii z Google Drive');if(!response.ok)await responseJson(response,'Usuwanie starej kopii z Google Drive');removed.push(file.name);}return removed;}
}

export class BackupManager{
  constructor({exportData,importData,settingsPath,localDirectory,googleDrive,now=()=>new Date()}){this.exportData=exportData;this.importData=importData;this.settingsPath=settingsPath;this.local=new LocalFileProvider(localDirectory);this.google=googleDrive;this.now=now;this.running=null;this.timer=null;}
  settings(){try{return{...DEFAULT_SETTINGS,...JSON.parse(fs.readFileSync(this.settingsPath,'utf8'))};}catch{return{...DEFAULT_SETTINGS};}}
  updateSettings(input){const interval=Number(input.interval_hours);if(!ALLOWED_INTERVALS.has(interval))throw new Error('Nieprawidłowy interwał kopii.');const next={...this.settings(),local_enabled:Boolean(input.local_enabled),drive_enabled:Boolean(input.drive_enabled),interval_hours:interval};if(!next.local_enabled&&!next.drive_enabled)throw new Error('Wybierz co najmniej jedno miejsce zapisu kopii.');writePrivateJson(this.settingsPath,next);return next;}
  status(){return{...this.settings(),google:this.google.status(),running:Boolean(this.running)};}
  async run(trigger='manual'){if(this.running)return this.running;this.running=this.performRun(trigger).finally(()=>{this.running=null;});return this.running;}
  async performRun(trigger){const settings=this.settings(),date=this.now(),stamp=date.toISOString(),filename=friendlyFilename(date,trigger),payload=this.exportData(),results=[],errors=[];if(settings.local_enabled)try{results.push(await this.local.save(payload,filename));await this.local.prune(3);}catch(error){errors.push(`Lokalnie: ${error.message}`);}if(settings.drive_enabled)try{results.push(await this.google.save(payload,filename));await this.google.prune(3);}catch(error){errors.push(`Google Drive: ${error.message}`);}const success=results.length>0&&errors.length===0,partial=results.length>0&&errors.length>0,next={...settings,last_run_at:stamp,last_success_at:results.length?stamp:settings.last_success_at,last_status:success?'success':partial?'partial':'error',last_message:errors.length?errors.join(' '):`Kopia „${filename}” zapisana: ${results.map(x=>x.provider==='local'?'lokalnie':'Google Drive').join(' + ')}.`,last_trigger:trigger};writePrivateJson(this.settingsPath,next);return{...next,results,errors};}
  async normalizeLegacyNames(){for(const file of await this.local.list()){const friendly=friendlyLegacyName(file.name);if(friendly)await this.local.rename(file.name,friendly);}if(this.google.status().connected)for(const file of await this.google.list()){const friendly=friendlyLegacyName(file.name);if(friendly)await this.google.rename(file.id,friendly);}}
  async enforceRetention(){const settings=this.settings();await this.normalizeLegacyNames();await this.local.prune(3);if(settings.drive_enabled&&this.google.status().connected)await this.google.prune(3);}
  async listBackups(){const local=await this.local.list();let drive=[],drive_error=null;if(this.google.status().connected)try{drive=await this.google.list();}catch(error){drive_error=error.message;}const copies=new Map();for(const file of [...local,...drive]){const current=copies.get(file.name)||{name:file.name,created_at:file.created_at,size:file.size,local:false,drive_id:null,sources:[]};if(file.created_at>current.created_at)current.created_at=file.created_at;if(file.provider==='local')current.local=true;else current.drive_id=file.id;current.sources.push(file.provider);copies.set(file.name,current);}return{files:[...copies.values()].sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,3),drive_error};}
  async restore({name,drive_id}){if(this.running)throw new Error('Poczekaj na zakończenie trwającej kopii.');this.running=this.performRestore({name,drive_id}).finally(()=>{this.running=null;});return this.running;}
  async performRestore({name,drive_id}){if(typeof this.importData!=='function')throw new Error('Przywracanie nie jest dostępne.');const payload=drive_id?await this.google.load(drive_id):await this.local.load(name);validateBackup(payload);const settings=this.settings(),date=this.now(),safetyName=friendlyFilename(date,'before_restore'),current=this.exportData(),safety=[];safety.push(await this.local.save(current,safetyName));if(settings.drive_enabled&&this.google.status().connected)safety.push(await this.google.save(current,safetyName));const imported=this.importData(payload);await this.local.prune(3);if(settings.drive_enabled&&this.google.status().connected)await this.google.prune(3);const stamp=date.toISOString(),next={...settings,last_restore_at:stamp,last_message:`Przywrócono kopię „${name}”. Przed zmianą zapisano kopię bezpieczeństwa.`};writePrivateJson(this.settingsPath,next);return{ok:true,name,source:drive_id?'drive':'local',imported,safety};}
  async runIfDue(){const settings=this.settings();if(!settings.interval_hours)return null;const baseline=settings.last_run_at?new Date(settings.last_run_at).getTime():0;if(Date.now()-baseline<settings.interval_hours*60*60*1000)return null;return this.run('schedule');}
  start(){if(this.timer)return;this.timer=setInterval(()=>this.runIfDue().catch(()=>{}),60_000);this.timer.unref?.();setTimeout(()=>this.runIfDue().catch(()=>{}),2_000).unref?.();setTimeout(()=>this.enforceRetention().catch(()=>{}),3_000).unref?.();}
  stop(){if(this.timer)clearInterval(this.timer);this.timer=null;}
}
